name = "FHL"
uuid = "e1f15e42-203f-4018-afb0-ea453ec53d7e"
authors = ["Sean Kell <sean.michael.kell@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
HTTP = "0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
